// engine/origfill - fill memory from an original AmigaOS executable streamed in once (ROADMAP 10.2a, docs/PUBLISHING.md).
// The game holds no byte of the original: the data of program and mog (DATA hunks, data cells in code hunks, the synth
// tables) is copied at start-up from the executables on the player's disk. A table of runs {destination, hunk, offset in the
// hunk, size} says what goes where (generated by tools/gen_data.py from our facts, tools/facts/<bin>.json); the stream is
// parsed as a hunk file (HUNK_HEADER, CODE/DATA/BSS, RELOC32, END, SYMBOL/DEBUG/NAME), every byte goes through a CRC-32
// that must equal the one of the known version. Relocations are not applied: a pointer cell is never a run (it is a
// link-time constant of our build), and the synth tables want the raw hunk offsets.
// Pure: no ACE, no OS, no globals; builds for the host tests as well as the Amiga.
#pragma once
#include <stdint.h>

namespace ms {

struct OrigFillRun {
	uint8_t *pDst;      // where the bytes go
	uint32_t ulSrc;     // offset in the hunk
	uint32_t ulSize;    // bytes
	uint16_t uwHunk;    // hunk number
};

// Reads up to ulCount bytes of the file into pDst, returns how many it read (0 = end of file / error).
typedef uint32_t (*OrigReadFn)(void *pCtx, uint8_t *pDst, uint32_t ulCount);

enum OrigFillResult : uint8_t {
	ORIG_OK = 0,
	ORIG_SHORT,        // the file ended early (or is shorter than the known version)
	ORIG_NOT_HUNK,     // not an AmigaOS executable
	ORIG_BAD_HUNK,     // a hunk structure this reader does not accept (or a run outside its hunk)
	ORIG_LONG,         // bytes after the last hunk / longer than the known version
	ORIG_CRC,          // a different version (CRC-32 mismatch)
};

struct OrigFillTable {
	const OrigFillRun *pRuns;
	uint32_t ulCount;
};

// Stream the whole file (exactly ulSize bytes are expected) and copy every run of the tables. *pCrc gets the CRC-32 of the
// file. Returns ORIG_CRC when it differs from ulCrc (the runs have been copied all the same: garbage, the caller stops).
OrigFillResult origFill(OrigReadFn fnRead, void *pCtx, uint32_t ulSize, uint32_t ulCrc, const OrigFillTable *pTables,
	unsigned uTables, uint32_t *pCrc);

// CRC-32 (IEEE 802.3, the one of zlib): crc32Update(0, p, n) of a whole buffer equals zlib.crc32().
uint32_t crc32Update(uint32_t ulCrc, const uint8_t *pData, uint32_t ulSize);

// Short English text of a result ("not an Amiga executable", ...).
const char *origFillText(OrigFillResult eResult);

}  // namespace ms
