"""rt entry -> the label of the original asm routine it replaced (the stub LAB_xxxx was `JMP rt_x`), for the ROADMAP 7.1q cutover: tests that link the C++ callers and
run the original routines in unicorn resolve the rt_* symbol to the oracle routine / its logging stub with this."""
RT_LABELS_Q = {
    'rt_mog_set_planes': 'LAB_0426+2',   # the stub sits at +2 (the first word of LAB_0426 is a mis-decoded CMPA)
    'rt_places_math_roll': 'LAB_045E',   # LAB_045E's first three instructions are inline in combat_ui.cpp now (LAB_05E4+10 := LAB_05E3[0])
    'rtNoop': 'LAB_0100',      # the disk prompt (a bare RTS in the game)
    'rtTitleStep': 'LAB_00B4',  # the title step (fade, Sel screen, hunk-9 chain, menu)
    'rtSceneKnightsRun': 'LAB_00D3',
    'rt_ar_arena_0168': 'LAB_0168',
    'rt_ar_arena_016a': 'LAB_016A',
    'rt_ar_arena_0175': 'LAB_0175',
    'rt_ar_arena_0188': 'LAB_0188',
    'rt_ar_arena_018c': 'LAB_018C',
    'rt_ar_arena_0196': 'LAB_0196',
    'rt_ar_arena_019a': 'LAB_019A',
    'rt_ar_arena_019e': 'LAB_019E',
    'rt_ar_arena_01a0': 'LAB_01A0',
    'rt_ar_init_0169': 'LAB_0169',
    'rt_ar_init_0170': 'LAB_0170',
    'rt_ar_init_0176': 'LAB_0176',
    'rt_ar_init_018b': 'LAB_018B',
    'rt_ar_init_018f': 'LAB_018F',
    'rt_ar_init_0198': 'LAB_0198',
    'rt_ar_init_019d': 'LAB_019D',
    'rt_ar_init_019f': 'LAB_019F',
    'rt_ar_swap_016b': 'LAB_016B',
    'rt_ar_swap_0189': 'LAB_0189',
    'rt_ar_swap_018d': 'LAB_018D',
    'rt_ar_swap_0197': 'LAB_0197',
    'rt_ar_swap_019b': 'LAB_019B',
    'rt_arena_dragon': 'LAB_0192',
    'rt_arena_meet': 'LAB_0164',
    'rt_blit_wait': 'LAB_0D1B',
    'rt_cl_select': 'LAB_012D',
    'rt_contact_scan': 'LAB_03BE',
    'rt_creature_spawn': 'LAB_02D0',
    'rt_cui_cursor_tick': 'LAB_057D',
    'rt_display_wait_frames': 'LAB_0D74',
    'rt_loot_click': 'LAB_052A',
    'rt_loot_drop': 'LAB_053D',
    'rt_loot_screen_setup': 'LAB_058A',
    'rt_mog_arena_default': 'LAB_0A6C',
    'rt_mog_arena_load': 'LAB_0A6D',
    'rt_mog_blit_both': 'LAB_0418',
    'rt_mog_blit_screen': 'LAB_0419',
    'rt_mog_cel_clip': 'LAB_0CCD',
    'rt_mog_cel_init': 'SECSTRT_28',
    'rt_mog_cel_load': 'LAB_0CBB',
    'rt_mog_cel_mirror': 'LAB_0CCE',
    'rt_mog_cel_scratch': 'SECSTRT_30',
    'rt_mog_cel_size': 'LAB_0CB6',
    'rt_mog_creature_clear': 'LAB_02CE',
    'rt_mog_display_flip': 'LAB_0416',
    'rt_mog_diw_shake_start': 'LAB_0427',
    'rt_mog_diw_shake_tick': 'LAB_042A',
    'rt_mog_draw_buf_clear': 'LAB_03A7',
    'rt_mog_draw_cel': 'LAB_0CDA',
    'rt_mog_fade_out': 'LAB_03F0',
    'rt_mog_fade_out_silent': 'LAB_03F1',
    'rt_mog_fade_to': 'LAB_03F2',
    'rt_mog_fight_palette_done': 'LAB_0413',
    'rt_mog_fight_palette_init': 'LAB_0412',
    'rt_mog_file_close': 'LAB_0BFF',
    'rt_mog_frame_wait': 'LAB_031F',
    'rt_mog_hit_load': 'LAB_03CE',
    'rt_mog_joy_read': 'LAB_00EE',
    'rt_mog_obstacles': 'LAB_0A71',
    'rt_mog_pair_load': 'LAB_02BA',
    'rt_mog_pic_file': 'LAB_0C27',
    'rt_mog_pic_mem': 'LAB_0C21',
    'rt_mog_restore_pass': 'LAB_039E',
    'rt_mog_sprite_build': 'SECSTRT_37',
    'rt_mog_sprite_place': 'LAB_0E78',
    'rt_mog_text_list': 'LAB_0432',
    'rt_rng_percent': 'LAB_04A3',
    'rt_scene_knights_run': 'LAB_00D3',
    'rt_synth_fade': 'LAB_0FC2',
    'rt_synth_init': 'LAB_0F89',
    'rt_synth_reloc': 'LAB_0FD4',
    'rt_synth_start': 'LAB_0F8C',
    'rt_synth_tick': 'LAB_0F73',
}
