// GENERATED by tools/resource.py from asm/patches/abs_symbols.json -- do not edit.
// Definitions of the rt_* DATA symbols the C++ runtime names (include/rt/abs.h): the work area and the low-memory cells they alias.
// (The rt_* functions are implemented in src/rt; the logging stubs of ROADMAP 1.4 are gone, ROADMAP 7.1f2.)
// The work area is a single CHIP block ($6BEFA..$80000 in the original memory map); the original sub-symbols are aliases into it.
// Everything is one top-level asm block, so -flto -fwhole-program cannot discard it.
#include <rt/abs.h>

asm(R"(
	.section .chipbss.MEMF_CHIP,"aw",@nobits
	.balign 4
	.globl rt_screen_work
rt_screen_work:
	.space 0x18086
	.globl rt_screen_clear
	.set rt_screen_clear, rt_screen_work+0x3f80
	.globl rt_screen_b
	.set rt_screen_b, rt_screen_work+0xbb82
	.globl rt_text_p0
	.set rt_text_p0, rt_screen_work+0x17708
	.globl rt_text_p1
	.set rt_text_p1, rt_screen_work+0x1770a
	.globl rt_text_x
	.set rt_text_x, rt_screen_work+0x1770c
	.globl rt_text_y
	.set rt_text_y, rt_screen_work+0x1770e
	.globl rt_trap_save_sp
	.set rt_trap_save_sp, rt_screen_work+0x17730
	.globl rt_copper_list
	.set rt_copper_list, rt_screen_work+0x17734
	.globl rt_copper_bpl1h
	.set rt_copper_bpl1h, rt_screen_work+0x17736
	.globl rt_copper_bpl1l
	.set rt_copper_bpl1l, rt_screen_work+0x1773a
	.globl rt_copper_bpl2h
	.set rt_copper_bpl2h, rt_screen_work+0x1773e
	.globl rt_copper_bpl2l
	.set rt_copper_bpl2l, rt_screen_work+0x17742
	.globl rt_copper_bpl3h
	.set rt_copper_bpl3h, rt_screen_work+0x17746
	.globl rt_copper_bpl3l
	.set rt_copper_bpl3l, rt_screen_work+0x1774a
	.globl rt_copper_bpl4h
	.set rt_copper_bpl4h, rt_screen_work+0x1774e
	.globl rt_copper_bpl4l
	.set rt_copper_bpl4l, rt_screen_work+0x17752
	.globl rt_copper_bpl5h
	.set rt_copper_bpl5h, rt_screen_work+0x17756
	.globl rt_copper_bpl5l
	.set rt_copper_bpl5l, rt_screen_work+0x1775a
	.globl rt_trk_block
	.set rt_trk_block, rt_screen_work+0x18050
	.globl rt_trk_state
	.set rt_trk_state, rt_screen_work+0x1805c
	.globl rt_trk_sector
	.set rt_trk_sector, rt_screen_work+0x18072
	.globl rt_trk_cylinder
	.set rt_trk_cylinder, rt_screen_work+0x18074
	.globl rt_screen_work_end
	.set rt_screen_work_end, rt_screen_work+0x18086

	.section .bss.rt_cells,"aw",@nobits
	.balign 2
	.globl rt_abs_a
rt_abs_a:	.space 2
	.globl rt_abs_c
rt_abs_c:	.space 2
	.globl rt_boot_flags
rt_boot_flags:	.space 2

	.text
)");
