// rt/image - DATA/BSS section table of the linked original binaries (generated by tools/resource.py).
#pragma once

namespace rt {

struct ImageSection {
	unsigned char *pBeg;   // first byte of the section (label emitted by resource.py)
	unsigned long ulSize;  // original hunk size in bytes
	bool isBss;            // true: zero at entry; false: DATA, restored from the snapshot
};

extern const ImageSection g_imageProgram[];
extern const unsigned g_imageProgramCount;
extern const ImageSection g_imageMog[];
extern const unsigned g_imageMogCount;

}  // namespace rt
