// GENERATED by tools/resource.py from asm/patches/abs_symbols.json -- do not edit.
// External symbols referenced by asm/program.s and asm/mog.s (ROADMAP 1.3/1.4).
#pragma once
#include <stdint.h>

#define RT_SCREEN_WORK_SIZE 0x18086u   // $6BEFA..$80000 of the original memory map

#ifdef __cplusplus
extern "C" {
#endif

// --- one contiguous CHIP block; every symbol below it is an alias at the original offset ---
extern uint8_t rt_screen_work[RT_SCREEN_WORK_SIZE];
extern uint8_t rt_screen_work_end[];
extern uint8_t rt_screen_clear[];  // $6BEFA start of the SECSTRT_29 / SECSTRT_34 clear loop (original base of the region)
extern uint8_t rt_screen_b[];  // $73AFC screen B (display/work swap partner, SECSTRT_30 cell 0 original value)
extern uint16_t rt_text_p0;  // $7F682 text/font cursor block: field 0 (loaded into D5)
extern uint16_t rt_text_p1;  // $7F684 text/font cursor block: field 1 (loaded into D4)
extern uint16_t rt_text_x;  // $7F686 text column byte offset
extern uint16_t rt_text_y;  // $7F688 text row (x $140 = scanline offset)
extern uint32_t rt_trap_save_sp;  // $7F6AA SP save slot of the (dead) TRAP #15 supervisor helper
extern uint32_t rt_copper_list;  // $7F6AE copper list base (COP1LCH)
extern uint16_t rt_copper_bpl1h;  // $7F6B0 copper slot BPL1PTH value
extern uint16_t rt_copper_bpl1l;  // $7F6B4 copper slot BPL1PTL value
extern uint16_t rt_copper_bpl2h;  // $7F6B8 
extern uint16_t rt_copper_bpl2l;  // $7F6BC 
extern uint16_t rt_copper_bpl3h;  // $7F6C0 
extern uint16_t rt_copper_bpl3l;  // $7F6C4 
extern uint16_t rt_copper_bpl4h;  // $7F6C8 
extern uint16_t rt_copper_bpl4l;  // $7F6CC 
extern uint16_t rt_copper_bpl5h;  // $7F6D0 
extern uint16_t rt_copper_bpl5l;  // $7F6D4 
extern uint8_t rt_trk_block[];  // $7FFCA trackdisk state block (LEA base)
extern uint16_t rt_trk_state;  // $7FFD6 trackdisk state word (1/2)
extern uint16_t rt_trk_sector;  // $7FFEC trackdisk: block mod 11
extern uint16_t rt_trk_cylinder;  // $7FFEE trackdisk: block / 22
// --- ordinary (fast) RAM cells the original kept in low memory ---
extern uint16_t rt_abs_a;  // $A word read from low memory (vector table junk) by mog LAB_02F8
extern uint16_t rt_abs_c;  // $C ADR_ERROR vector word read by mog LAB_02F8
extern uint16_t rt_boot_flags;  // $3E0 boot flags word shared by program/mog (bit 7 = diag branch)
// --- functions the patch sites call, each implemented in the src/rt file named after it ---
void rt_irq_disable(void);  // src/rt/irq.cpp
void rt_irq_enable(void);  // src/rt/irq.cpp
void rt_prg_intro_begin(void);  // src/rt/introskip.cpp
void rt_prg_wait_beam(void);  // src/rt/introskip.cpp
void rt_rnc_decode(void);  // src/rt/engine_rnc.cpp
void rt_rng_percent(void);  // src/rt/engine_util.cpp
void rt_job_reset(void);  // src/rt/engine_jobs.cpp
void rt_palette_set_target_prg(void);  // src/rt/engine_palette.cpp
void rt_palette_ramp_add_prg(void);  // src/rt/engine_palette.cpp
void rt_palette_tick_prg(void);  // src/rt/engine_palette.cpp
void rt_palette_set_target_mog(void);  // src/rt/engine_palette.cpp
void rt_palette_cycle_add_mog(void);  // src/rt/engine_palette.cpp
void rt_palette_ramp_add_mog(void);  // src/rt/engine_palette.cpp
void rt_palette_tick_mog(void);  // src/rt/engine_palette.cpp
void rt_prg_draw_cel(void);  // src/rt/engine_blit.cpp
void rt_mog_draw_cel(void);  // src/rt/engine_blit.cpp
void rt_prg_copy_rect(void);  // src/rt/engine_blit.cpp
void rt_prg_copy_rect_desc(void);  // src/rt/engine_blit.cpp
void rt_prg_intro_run(void);  // src/rt/engine_intro.cpp
void rt_knight_recalc_hp(void);  // src/rt/game_rules.cpp
void rt_knight_recalc_endurance(void);  // src/rt/game_rules.cpp
void rt_music_start(void);  // src/rt/audio.cpp
void rt_music_stop(void);  // src/rt/audio.cpp
void rt_audio_quiesce_mog(void);  // src/rt/audio.cpp
void rt_combat_tick(void);  // src/rt/combat_script.cpp
void rt_places_math_roll(void);  // src/rt/scene_places.cpp
void rt_places_gift_gold(void);  // src/rt/scene_places.cpp
void rt_places_gift_item(void);  // src/rt/scene_places.cpp
void rt_fight_run(void);  // src/rt/combat.cpp
void rt_fight_meet(void);  // src/rt/combat.cpp
void rt_fight_creature(void);  // src/rt/combat.cpp
void rt_fight_dragon(void);  // src/rt/combat.cpp
void rt_arena_meet(void);  // src/rt/combat.cpp
void rt_arena_dragon(void);  // src/rt/combat.cpp
void rt_screen_run(void);  // src/rt/combat.cpp
void rt_screen_redraw(void);  // src/rt/combat.cpp
void rt_contact_scan(void);  // src/rt/creatures.cpp
void rt_job_create(void);  // src/rt/creatures.cpp
void rt_creature_spawn(void);  // src/rt/creatures.cpp
void rt_creature_dispatch(void);  // src/rt/creatures.cpp
void rt_ow_dragon_fly(void);  // src/rt/overworld.cpp
void rt_mog_main(void);  // src/rt/mainloop.cpp
void rt_mog_quit(void);  // src/rt/mainloop.cpp
void rt_mog_jobs_reset(void);  // src/rt/mainloop.cpp
void rt_mog_job_toggle(void);  // src/rt/mainloop.cpp
void rt_mog_frame_start(void);  // src/rt/mainloop.cpp
void rt_mog_frame_wait(void);  // src/rt/mainloop.cpp
void rt_prg_pal_copy_live(void);  // src/rt/enhanced.cpp
void rt_mog_carve(void);  // src/rt/enhanced.cpp
void rt_mog_pal_copy_live(void);  // src/rt/enhanced.cpp
void rt_mog_pack_done(void);  // src/rt/enhanced.cpp
void rt_prg_text_list(void);  // src/rt/gtext.cpp
void rt_mog_text_list(void);  // src/rt/gtext.cpp
void rt_mog_text_string(void);  // src/rt/gtext.cpp
void rt_mog_add_record(void);  // src/rt/gtext.cpp
void rt_prg_cel_init(void);  // src/rt/engine_blit.cpp
void rt_prg_cel_clip(void);  // src/rt/engine_blit.cpp
void rt_prg_cel_mirror(void);  // src/rt/engine_blit.cpp
void rt_prg_cel_scratch(void);  // src/rt/engine_blit.cpp
void rt_mog_cel_init(void);  // src/rt/engine_blit.cpp
void rt_mog_cel_clip(void);  // src/rt/engine_blit.cpp
void rt_mog_cel_mirror(void);  // src/rt/engine_blit.cpp
void rt_mog_cel_scratch(void);  // src/rt/engine_blit.cpp
void rt_blit_wait(void);  // src/rt/engine_blit.cpp
void rt_prg_pic_mem(void);  // src/rt/loaders.cpp
void rt_prg_pic_file(void);  // src/rt/loaders.cpp
void rt_prg_cel_load(void);  // src/rt/loaders.cpp
void rt_prg_cel_size(void);  // src/rt/loaders.cpp
void rt_mog_pic_mem(void);  // src/rt/loaders.cpp
void rt_mog_pic_file(void);  // src/rt/loaders.cpp
void rt_mog_cel_load(void);  // src/rt/loaders.cpp
void rt_mog_cel_size(void);  // src/rt/loaders.cpp
void rt_mog_hit_load(void);  // src/rt/loaders.cpp
void rt_prg_irq_init(void);  // src/rt/irq.cpp
void rt_mog_irq_init(void);  // src/rt/irq.cpp
void rt_prg_key_reset(void);  // src/rt/input.cpp
void rt_mog_key_reset(void);  // src/rt/input.cpp
void rt_mog_key_wait(void);  // src/rt/input.cpp
void rt_mog_joy_read(void);  // src/rt/input.cpp
void rt_mog_wait_fire(void);  // src/rt/input.cpp
void rt_mog_cursor_on(void);  // src/rt/input.cpp
void rt_mog_cursor_off(void);  // src/rt/input.cpp
void rt_job_handler_stop(void);  // src/rt/engine_scenes.cpp
void rt_scn_message(void);  // src/rt/engine_scenes.cpp
void rt_prg_anim_init(void);  // src/rt/engine_scenes.cpp
void rt_prg_ending_run(void);  // src/rt/engine_intro.cpp
void rt_ar_arena_0168(void);  // src/rt/arena.cpp
void rt_ar_init_0169(void);  // src/rt/arena.cpp
void rt_ar_arena_016a(void);  // src/rt/arena.cpp
void rt_ar_swap_016b(void);  // src/rt/arena.cpp
void rt_ar_init_0170(void);  // src/rt/arena.cpp
void rt_ar_arena_0175(void);  // src/rt/arena.cpp
void rt_ar_init_0176(void);  // src/rt/arena.cpp
void rt_ar_arena_0188(void);  // src/rt/arena.cpp
void rt_ar_swap_0189(void);  // src/rt/arena.cpp
void rt_ar_init_018b(void);  // src/rt/arena.cpp
void rt_ar_arena_018c(void);  // src/rt/arena.cpp
void rt_ar_swap_018d(void);  // src/rt/arena.cpp
void rt_ar_init_018f(void);  // src/rt/arena.cpp
void rt_ar_arena_0196(void);  // src/rt/arena.cpp
void rt_ar_swap_0197(void);  // src/rt/arena.cpp
void rt_ar_init_0198(void);  // src/rt/arena.cpp
void rt_ar_arena_019a(void);  // src/rt/arena.cpp
void rt_ar_swap_019b(void);  // src/rt/arena.cpp
void rt_ar_init_019d(void);  // src/rt/arena.cpp
void rt_ar_arena_019e(void);  // src/rt/arena.cpp
void rt_ar_init_019f(void);  // src/rt/arena.cpp
void rt_ar_arena_01a0(void);  // src/rt/arena.cpp
void rt_cui_cursor_tick(void);  // src/rt/combat_ui.cpp
void rt_mog_palette_clear(void);  // src/rt/palette_glue.cpp
void rt_mog_fade_out(void);  // src/rt/palette_glue.cpp
void rt_mog_fade_out_silent(void);  // src/rt/palette_glue.cpp
void rt_mog_fade_to(void);  // src/rt/palette_glue.cpp
void rt_mog_palette_scene(void);  // src/rt/palette_glue.cpp
void rt_mog_fight_palette_init(void);  // src/rt/palette_glue.cpp
void rt_mog_fight_palette_done(void);  // src/rt/palette_glue.cpp
void rt_mog_display_flip(void);  // src/rt/mog_display.cpp
void rt_mog_blit_both(void);  // src/rt/mog_display.cpp
void rt_mog_blit_screen(void);  // src/rt/mog_display.cpp
void rt_mog_diw_shake_start(void);  // src/rt/mog_display.cpp
void rt_mog_diw_shake_tick(void);  // src/rt/mog_display.cpp
void rt_mog_display_init(void);  // src/rt/display_ops.cpp
void rt_display_wait_frames(void);  // src/rt/display_ops.cpp
void rt_display_palette_write(void);  // src/rt/display_ops.cpp
void rt_mog_key_xlat(void);  // src/rt/display_ops.cpp
void rt_mog_palette_hook_add(void);  // src/rt/palette_glue.cpp
void rt_palette_slot_free(void);  // src/rt/palette_glue.cpp
void rt_mog_sprite_build(void);  // src/rt/sprites.cpp
void rt_mog_sprite_place(void);  // src/rt/sprites.cpp
void rt_mog_restore_pass(void);  // src/rt/prims.cpp
void rt_mog_draw_buf_clear(void);  // src/rt/prims.cpp
void rt_mog_pair_load(void);  // src/rt/prims.cpp
void rt_mog_creature_clear(void);  // src/rt/prims.cpp
void rt_mog_dagger_clear(void);  // src/rt/prims.cpp
void rt_mog_job_boot(void);  // src/rt/prims.cpp
void rt_mog_set_planes(void);  // src/rt/prims.cpp
void rt_mog_arena_default(void);  // src/rt/arena_bg.cpp
void rt_mog_arena_load(void);  // src/rt/arena_bg.cpp
void rt_mog_obstacles(void);  // src/rt/arena_bg.cpp
void rt_scr_mystic(void);  // src/rt/screens.cpp
void rt_scr_healer(void);  // src/rt/screens.cpp
void rt_scr_dice(void);  // src/rt/screens.cpp
void rt_scr_ritual(void);  // src/rt/screens.cpp
void rt_scr_lines(void);  // src/rt/screens.cpp
void rt_scr_ramp5(void);  // src/rt/screens.cpp
void rt_scr_dice_idle(void);  // src/rt/screens.cpp
void rt_scr_ritual_done(void);  // src/rt/screens.cpp
void rt_synth_init(void);  // src/rt/synth.cpp
void rt_synth_reloc(void);  // src/rt/synth.cpp
void rt_synth_start(void);  // src/rt/synth.cpp
void rt_synth_tick(void);  // src/rt/synth.cpp
void rt_synth_fade(void);  // src/rt/synth.cpp
void rt_prg_main(void);  // src/rt/progmain.cpp
void rt_prg_display_init(void);  // src/rt/display_ops.cpp
void rt_prg_display_swap(void);  // src/rt/display_ops.cpp
void rt_prg_palette_hook_add(void);  // src/rt/palette_glue.cpp
void rt_prg_restore_pass(void);  // src/rt/prims.cpp
// --- overlay-chain entries (ROADMAP 1.5): tail-jumped to by the asm, never return; src/rt/game.cpp ---
void rt_run_mog(void);
void rt_run_program(void);
void rt_prg_file_init(void);
void rt_prg_file_open(void);
void rt_prg_file_read(void);
void rt_prg_file_close(void);
void rt_mog_file_close(void);
#ifdef __cplusplus
}
#endif
