#!/usr/bin/env python3
"""lift.py -- mechanical 68000 asm -> C++ transliterator (ROADMAP 3.5).

Turns one original routine of the reassembled listing (build/reasm/<bin>.asm, address
data from <bin>.lst / <bin>.symbols.json, boundaries from build/inventory/<bin>.callgraph.json)
into

    extern "C" void lab_<LABEL>(ms::Regs& R, ms::Mem& M)

written to src/lifted/<bin>/lab_<label>.cpp using include/ms/regs.hpp.  Each asm label becomes
a C label, branches become goto, instructions become one statement each with the exact 68000
flag behaviour (see tools/lift_emit.py).  Anything not understood fails loudly with the asm
line number; no code is guessed.

Usage
  py tools/lift.py mog LAB_03CA --out-dir <dir>      # one routine (never overwrites hand-written files)
  py tools/lift.py --all-pure-leaves [--bins mog program] [--prove] [--n 500]
  py tools/lift.py --gen-headers                      # include/ms/gen/{lift_ops,<bin>_syms}.hpp only
  py tools/lift.py --equiv-pilot                      # lift LAB_03CA to a temp dir, replay the pilot's cases

Naming (so every routine of every binary can live in one build)
  * mog:            function lab_<LABEL>           case file tests/diff/mog/<LABEL>.json
  * other binaries: function lab_<bin>_<LABEL>     case file tests/diff/<bin>/<bin>_<LABEL>.json
  run_host.py's registry is keyed by the text after `lab_` and C symbols are global, so labels that
  exist in several binaries (LAB_0003 is in mog and program) must not share a function name.
  The harness itself is still called with the plain label.

Symbols (absolute / label operands)
  Operands such as `MOVE.W D0,LAB_08C4` become `M.w16(MS_SYM(mog, LAB_08C4), ...)`.  The generated
  include/ms/gen/<bin>_syms.hpp defines every asm label as a constexpr address in the *harness
  layout* (hunks packed at IMAGE_BASE exactly as harness.load_image does) plus HUNK_hh bases, used
  for JSR return addresses.  The MS_SYM/MS_HUNK macros are #ifndef-guarded in lift_ops.hpp so a
  linked build can predefine them with its own addresses.

Calls
  JSR/BSR (and BRA/JMP/Bcc out of the routine, as tail calls) to a routine that has a lifted
  function become `M.w32(R.a[7]-4, <return addr>); lab_X(R, M);` -- the return address is stored
  below SP exactly like the real JSR so dirty-memory comparisons match.  Otherwise the routine is
  refused unless --allow-calls, which emits `lift::callAsm(R, M, addr)` (declared in lift_ops.hpp;
  the default body traps -- the thunk layer provides the real one).
"""
import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "diffharness"))
import lift_ops  # noqa: E402
from lift_emit import Emitter, suffix  # noqa: E402
from lift_parse import Program, Unsupported, ROOT  # noqa: E402

LIFTED = ROOT / "src" / "lifted"
GEN = ROOT / "include" / "ms" / "gen"
MARK = "GENERATED by tools/lift.py"
DEFN = re.compile(r'extern\s+"C"\s+void\s+lab_(\w+)\s*\(')


class HandWritten(Exception):
    pass


# ------------------------------------------------------------------------------ naming
def file_stem(label):
    label = label.replace("+", "_p")
    s = label[4:] if label.startswith("LAB_") else label
    return "lab_" + s.lower()


def lifted_suffixes(binary, extra_dir=None):
    """Registry suffixes (text after lab_) defined under src/lifted/<binary> (+ extra_dir)."""
    out = {}
    roots = [LIFTED / binary] + ([extra_dir] if extra_dir else [])
    for d in roots:
        if d.exists():
            for p in d.rglob("*.cpp"):
                for m in DEFN.finditer(p.read_text()):
                    out[m.group(1)] = p
    return out


# ------------------------------------------------------------------------------ headers
def write_if_changed(path, text):
    """Write only when the content differs (keeps mtimes stable); retry transient Windows errors."""
    import time
    for attempt in range(5):
        try:
            if path.exists() and path.read_text() == text:
                return
            path.write_text(text)
            return
        except OSError:
            if attempt == 4:
                raise
            time.sleep(0.5)


def gen_headers(binaries):
    import harness
    GEN.mkdir(parents=True, exist_ok=True)
    write_if_changed(GEN / "lift_ops.hpp", lift_ops.HEADER)
    for b in binaries:
        img, bases = harness.load_image(ROOT / "build" / "reasm" / b)
        prog = Program(b)
        sha = hashlib.sha1(img).hexdigest()
        L = ["// include/ms/gen/%s_syms.hpp - %s (tools/lift.py --gen-headers); do not edit." % (b, MARK),
             "// Label addresses of build/reasm/%s in the differential-harness layout:" % b,
             "// hunks packed back to back from IMAGE_BASE=$%08X; image sha1 %s." % (bases[0], sha),
             "// Regenerate after `py tools/reassemble.py`; see tools/lift.py for the MS_SYM scheme.",
             "#pragma once", '#include "ms/regs.hpp"', "namespace ms {", "namespace sym_%s {" % b]
        for i, base in enumerate(bases):
            L.append("constexpr uint32_t HUNK_%02X = 0x%08Xu;" % (i, base))
        for name, (h, off) in sorted(prog.labels.items()):
            L.append("constexpr uint32_t %s = HUNK_%02X + 0x%Xu;" % (name, h, off))
        L += ["} // namespace sym_%s" % b, "} // namespace ms", ""]
        write_if_changed(GEN / ("%s_syms.hpp" % b), "\n".join(L))


# ------------------------------------------------------------------------------ one routine
def lift_routine(prog, name, known, allow_calls=False):
    """-> (source text, Emitter).  `known` = set of routine names that have a lifted function."""
    insns, labels = prog.parse_routine(name)
    em = Emitter(prog, name, insns, labels, known, allow_calls)
    body = em.routine_body()
    r = prog.routines[name]
    b = prog.binary
    fn = "lab_" + suffix(b, name)
    L = ["// %s.asm lines %d-%d: %s (hunk %02X offset $%X, %d bytes)." %
         (b, r["line_first"], r["line_last"], name, r["hunk"], r["start"], r["size"]),
         "// %s - do not edit; fix tools/lift.py and regenerate." % MARK,
         "// Literal transliteration: one statement per instruction, CCR as the 68000 leaves it.",
         '#include "ms/regs.hpp"', '#include "ms/gen/lift_ops.hpp"']
    if em.uses_sym:
        L.append('#include "ms/gen/%s_syms.hpp"' % b)
    L += ["using namespace ms;", ""]
    for c in em.callees:
        if c != name:
            # block form on purpose: run_host.py's registry regex matches `extern "C" void lab_X(`
            # and would mistake a declaration for the definition.
            L.append('extern "C" { void lab_%s(Regs&, Mem&); }' % suffix(b, c))
    L.append('extern "C" void %s(Regs& R, Mem& M) {' % fn)
    L.append("    (void)R; (void)M;")
    if em.uses_stack:
        L.append("    R.a[7] -= 4u;  // a[7] on entry is after the return-address pop; the original runs at the slot")
    L += body
    L += ["}", ""]
    return "\n".join(L), em


def write_routine(prog, name, outdir, known, allow_calls=False):
    src, em = lift_routine(prog, name, known, allow_calls)
    outdir.mkdir(parents=True, exist_ok=True)
    p = outdir / (file_stem(name) + ".cpp")
    if p.exists() and MARK not in p.read_text():
        raise HandWritten("refusing to overwrite hand-written %s" % p)
    p.write_text(src)
    return p, em


# ------------------------------------------------------------------------------ selection
def is_pure_leaf(prog, r):
    if not (r["leaf"] and r["ends_in"] == "RTS" and not r["hardware"]):
        return False
    lo, hi = r["line_first"], r["line_last"]
    if any(lo <= (ln or 0) <= hi for ln in prog.indirect_lines):
        return False
    return not any(e["caller"] == r["name"] and e["kind"] not in ("bra", "bcc") and e["callee_routine"] != r["name"]
                   and e["kind"] in ("jsr", "jmp", "bsr") for e in prog.edges)


def pure_candidates(prog):
    """Closure mode: any routine that ends in RTS, a tail BRA/JMP or a fall-through into the next
    routine, with no hardware/indirect jump; the lifter itself refuses (call or tail call to
    non-lifted) until every callee has been lifted."""
    out = []
    for n, r in prog.routines.items():
        lo, hi = r["line_first"], r["line_last"]
        if r["ends_in"] in ("RTS", "BRA", "JMP", "fallthrough") and not r["hardware"] and \
                not any(lo <= (ln or 0) <= hi for ln in prog.indirect_lines):
            out.append(n)
    return out


def pure_leaves(prog):
    return [n for n, r in prog.routines.items() if is_pure_leaf(prog, r)]


# ------------------------------------------------------------------------------ proving
def compact_write_cases(h, binary, label, stem, cases, seed):
    doc = h.header(label)
    doc["seed"] = seed
    doc["cases"] = cases
    p = ROOT / "tests" / "diff" / binary / (stem + ".json")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(doc, separators=(",", ":")) + "\n")
    h.write_image()
    return p


def gen_cases(h, prog, binary, name, em, n, seed):
    """Fuzz n cases.  Stock harness fuzz first (pointer A-registers when the routine dereferences
    An); if that yields too few non-faulting cases, the pointer-graph fuzzer in lift_fuzz.py.
    -> (count, mode, skipped)"""
    import lift_fuzz
    lift_fuzz.guard(h)
    rr = prog.routines[name]
    h.symbols.setdefault(name, {"hunk": rr["hunk"], "offset": rr["start"]})   # e.g. 'LAB_0426+2' has no label
    best = (None, "", {})
    for ptr in ([True, False] if em.has_mem_an else [False, True]):
        cases, skipped = h.fuzz(name, n, seed, ptr_aregs=ptr, max_tries_factor=2)
        if best[0] is None or len(cases) > len(best[0]):
            best = (cases, "ptr" if ptr else "rand", skipped)
        if len(cases) >= n:
            break
    if len(best[0]) < n:
        cells = sorted({h.hunk_bases[prog.labels[s][0]] + prog.labels[s][1] + add
                        for s, add in em.sym_refs if prog.hunk_kind[prog.labels[s][0]] != "CODE"})
        cases, skipped = lift_fuzz.fuzz(h, name, n, seed, cells)
        if len(cases) > len(best[0]):
            best = (cases, "graph", skipped)
    cases, mode, skipped = best
    # replay_main.cpp holds at most 64 memory/write runs per case (fixed arrays); more would overflow it.
    cases = [c for c in cases if len(c["writes"]) <= 60 and len(c["mem_in"]) <= 60]
    if cases:
        compact_write_cases(h, binary, name, suffix(binary, name), cases, seed)
    return len(cases), mode, skipped


# ------------------------------------------------------------------------------ batch
def batch(binaries, prove, n, seed, limit, allow_calls, closure, only=(), resume=False):
    import harness
    totals = {"selected": 0, "lifted": 0, "unsupported": 0, "cases_ok": 0, "cases_short": 0, "nocases": 0}
    unsup = Counter()
    unsup_detail = []
    results = []
    for b in binaries:
        prog = Program(b)
        known = set()
        for suf in lifted_suffixes(b):
            known.add(suf if b == "mog" else suf[len(b) + 1:])
        sel = pure_candidates(prog) if closure else pure_leaves(prog)
        if only:
            sel = [x for x in sel if x in only]
        if limit:
            sel = sel[:limit]
        totals["selected"] += len(sel)
        h = harness.Harness(b) if prove else None
        pending = list(sel)
        last_err = {}
        while pending:
            nxt = []
            for name in pending:
                try:
                    p, em = write_routine(prog, name, LIFTED / b, known | {name}, allow_calls)
                except HandWritten:
                    totals["handwritten"] = totals.get("handwritten", 0) + 1
                    known.add(name)
                    continue
                except Unsupported as e:
                    last_err[name] = e
                    nxt.append(name)
                    continue
                known.add(name)
                last_err.pop(name, None)
                totals["lifted"] += 1
                cf = ROOT / "tests" / "diff" / b / (suffix(b, name) + ".json")
                if prove and resume and cf.exists():
                    cnt = len(json.loads(cf.read_text())["cases"])
                    results.append((b, name, cnt, "resumed", {}))
                    totals["cases_ok" if cnt >= n else "cases_short"] += 1
                elif prove:
                    cnt, mode, skipped = gen_cases(h, prog, b, name, em, n, seed)
                    results.append((b, name, cnt, mode, skipped))
                    print("  case %s/%s: %d cases (%s) skipped=%s" % (b, name, cnt, mode, skipped or "-"), flush=True)
                    if cnt >= n:
                        totals["cases_ok"] += 1
                    elif cnt:
                        totals["cases_short"] += 1
                    else:
                        totals["nocases"] += 1
            if not closure or len(nxt) == len(pending):
                pending = nxt
                break
            pending = nxt
        for name in pending:
            e = last_err[name]
            unsup[e.key] += 1
            unsup_detail.append((b, name, e.key, str(e)))
        # routines never lifted
    return totals, unsup, unsup_detail, results


def survey(binaries):
    """Lift every routine (calls allowed, nothing written) and count what the lifter cannot do.
    Parse failures abort a routine at the first bad line; emit failures are counted per instruction."""
    cnt, routines_ok, routines_total, parse_fail = Counter(), 0, 0, Counter()
    for b in binaries:
        prog = Program(b)
        names = set(prog.routines)
        for name, r in prog.routines.items():
            if r["ends_in"] == "data":
                continue
            routines_total += 1
            try:
                insns, labels = prog.parse_routine(name)
            except Unsupported as e:
                cnt[e.key] += 1
                parse_fail[e.key] += 1
                continue
            em = Emitter(prog, name, insns, labels, names, True)
            bad = 0
            for ins in insns:
                try:
                    em.emit_insn(ins)
                except Unsupported as e:
                    cnt[e.key] += 1
                    bad += 1
            routines_ok += bad == 0
    print("survey of %s: %d routines, %d lift completely (calls allowed)" % (" ".join(binaries), routines_total, routines_ok))
    print("unsupported occurrences ranked (parse failures count once per routine):")
    for k, c in cnt.most_common():
        print("  %-34s %d" % (k, c))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("binary", nargs="?")
    ap.add_argument("label", nargs="?")
    ap.add_argument("--out-dir")
    ap.add_argument("--allow-calls", action="store_true")
    ap.add_argument("--closure", action="store_true",
                    help="with --all-pure-leaves: also lift non-leaf routines whose callees all got lifted")
    ap.add_argument("--all-pure-leaves", action="store_true")
    ap.add_argument("--bins", nargs="*", default=["mog", "program"])
    ap.add_argument("--prove", action="store_true", help="generate fuzz cases for every lifted routine")
    ap.add_argument("--n", type=int, default=500)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--only", nargs="*", default=[], help="restrict --all-pure-leaves to these routine names")
    ap.add_argument("--resume", action="store_true", help="--prove: keep existing case files")
    ap.add_argument("--survey", action="store_true", help="count unsupported opcodes over all routines")
    ap.add_argument("--sync-status", action="store_true",
                    help="replay all cases and set status in tools/symbols.yaml (tools/status.py)")
    ap.add_argument("--gen-headers", action="store_true")
    ap.add_argument("--equiv-pilot", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    a = ap.parse_args()

    if a.survey:
        return survey(a.bins) or 0
    if a.sync_status:
        import status
        return status.main(["--sync"])
    if a.gen_headers or a.all_pure_leaves or a.equiv_pilot or a.binary:
        gen_headers(sorted(set(a.bins) | ({a.binary} if a.binary else set()) | ({"mog"} if a.equiv_pilot else set())))
    if a.gen_headers and not (a.all_pure_leaves or a.binary or a.equiv_pilot):
        return 0
    if a.equiv_pilot:
        return equiv_pilot(a.n)
    if a.all_pure_leaves:
        totals, unsup, detail, results = batch(a.bins, a.prove, a.n, a.seed, a.limit, a.allow_calls, a.closure, set(a.only), a.resume)
        print("selected %(selected)d  lifted %(lifted)d  (already hand-written: %(hw)d)" % dict(totals, hw=totals.get("handwritten", 0)))
        print("unsupported: %d" % sum(unsup.values()))
        for k, c in unsup.most_common():
            print("  %-34s %d" % (k, c))
        shown = 0
        for b, name, key, msg in detail:
            if key == "call to non-lifted routine":
                shown += 1
                if shown > 12:
                    continue
            print("  %s/%s: %s" % (b, name, msg))
        if a.prove:
            print("cases: >=%d for %d routines, fewer for %d, none for %d" %
                  (a.n, totals["cases_ok"], totals["cases_short"], totals["nocases"]))
        return 0
    if not (a.binary and a.label):
        ap.error("need <binary> <LABEL> or --all-pure-leaves")
    prog = Program(a.binary)
    if a.label not in prog.routines:
        sys.exit("%s: no routine %s in callgraph" % (a.binary, a.label))
    known = set()
    for s in lifted_suffixes(a.binary):
        known.add(s if a.binary == "mog" else s[len(a.binary) + 1:])
    try:
        if a.stdout:
            print(lift_routine(prog, a.label, known | {a.label}, a.allow_calls)[0])
            return 0
        p, em = write_routine(prog, a.label, Path(a.out_dir) if a.out_dir else LIFTED / a.binary,
                              known | {a.label}, a.allow_calls)
    except HandWritten as e:
        print(e, file=sys.stderr)
        return 1
    except Unsupported as e:
        print("UNSUPPORTED [%s] %s/%s: %s" % (e.key, a.binary, a.label, e), file=sys.stderr)
        return 1
    print("wrote", p)
    return 0


def equiv_pilot(n):
    """Lift LAB_03CA into a temp dir and replay tests/diff/mog/LAB_03CA.json against it."""
    import subprocess
    import run_host
    prog = Program("mog")
    tmp = Path(tempfile.mkdtemp(prefix="lift_pilot_"))
    try:
        (tmp / "mog").mkdir()
        p, _ = write_routine(prog, "LAB_03CA", tmp / "mog", {"LAB_03CA"})
        print("lifted to", p)
        run_host.LIFTED = tmp
        found = run_host.scan()
        run_host.OUT = ROOT / "build" / "diff" / "host_pilot"
        exe = run_host.build(found)
        doc = json.loads((ROOT / "tests" / "diff" / "mog" / "LAB_03CA.json").read_text())
        run_host.harness.write_cases  # noqa: B018 (module is imported)
        txt = run_host.OUT / "mog_LAB_03CA.cases"
        txt.write_text(run_host.harness.cases_to_text(doc))
        (ROOT / "build" / "diff" / "mog.img").exists() or sys.exit("run run_host.py once to create build/diff/mog.img")
        r = subprocess.run([str(exe), str(ROOT), "LAB_03CA", "mog", str(txt)])
        return r.returncode
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
