"""lift_ops.py -- the support header emitted as include/ms/gen/lift_ops.hpp.

regs.hpp (hand-written, not modified by the lifter project) covers the common ALU
ops.  Everything else the lifter needs lives here, in namespace ms::lift:
DIVU/DIVS, bit ops, TAS, and the two hooks for code that is not lifted.
Header-only, no STL; builds with clang++ (host replay) and m68k-amiga-elf-g++.
"""

HEADER = r'''// include/ms/gen/lift_ops.hpp - GENERATED by tools/lift_ops.py (via tools/lift.py); do not edit.
// Support routines for lifted code that regs.hpp does not provide.
#pragma once
#include "ms/regs.hpp"

// ---- symbol addresses ---------------------------------------------------------------
// Lifted code names asm labels as MS_SYM(<bin>, LAB_xxxx) and hunk-relative return
// addresses as MS_HUNK(<bin>, hh) + offset.  The default definition (generated
// include/ms/gen/<bin>_syms.hpp) is the *differential harness layout*: the reassembled hunks
// packed back to back at IMAGE_BASE=$00100000 (tools/diffharness/harness.py load_image).
// A build that links the original data at other addresses overrides the macros *before*
// including lifted sources (e.g. to `extern "C" const char ms_<bin>_<label>[]` symbols).
#ifndef MS_SYM
#define MS_SYM(bin, label)  (::ms::sym_##bin::label)
#define MS_HUNK(bin, hh)    (::ms::sym_##bin::HUNK_##hh)
#endif

namespace ms {
namespace lift {

// Hook for code that is not lifted: run the original routine at 68k address `addr` with
// the lifted calling convention (return address already written below a[7], a[7] is the
// SP *after* the pop, RTS = return).  The host replay has no emulator, so the default
// traps; the thunk layer (ROADMAP 3.2) provides the real implementation.
inline void callAsm(Regs&, Mem&, uint32_t) { __builtin_trap(); }

// Zero divisor: the CPU takes the divide-by-zero exception (vector 5).
inline void zeroDivide(Regs&, Mem&) { __builtin_trap(); }

// DIVU/DIVS Dn: dn = (remainder << 16) | quotient.  Returns false for a zero divisor.
// Overflow (quotient does not fit 16 bits): Dn unchanged, V=1, C=0, Z=0, N and X left
// as they were -- what the reference emulator (unicorn/QEMU) does; N/Z are architecturally
// undefined on the 68000 here.
inline bool divu(Regs& r, uint32_t& dn, uint32_t src) {
    uint32_t s = src & 0xFFFFu;
    if (s == 0) return false;
    uint32_t q = dn / s, rem = dn % s;
    if (q > 0xFFFFu) { r.setNZVC(r.N(), false, true, false); return true; }
    dn = (rem << 16) | q;
    r.setNZVC((q & 0x8000u) != 0, q == 0, false, false);
    return true;
}
inline bool divs(Regs& r, uint32_t& dn, uint32_t src) {
    int32_t s = (int32_t)(int16_t)(uint16_t)src;
    if (s == 0) return false;
    int32_t d = (int32_t)dn;
    if (d == (int32_t)0x80000000 && s == -1) { r.setNZVC(r.N(), false, true, false); return true; }
    int32_t q = d / s, rem = d % s;
    if (q > 32767 || q < -32768) { r.setNZVC(r.N(), false, true, false); return true; }
    dn = ((uint32_t)rem << 16) | ((uint32_t)q & 0xFFFFu);
    r.setNZVC((q & 0x8000) != 0, q == 0, false, false);
    return true;
}

// Bit operations: Z = old bit was 0.  BITS = 32 for Dn destinations, 8 for memory bytes.
template <unsigned BITS> inline void btst(Regs& r, uint32_t v, uint32_t bit) {
    r.setFlag(CCR_Z, ((v >> (bit % BITS)) & 1u) == 0);
}
template <unsigned BITS> inline uint32_t bset(Regs& r, uint32_t v, uint32_t bit) {
    btst<BITS>(r, v, bit); return v | (1u << (bit % BITS));
}
template <unsigned BITS> inline uint32_t bclr(Regs& r, uint32_t v, uint32_t bit) {
    btst<BITS>(r, v, bit); return v & ~(1u << (bit % BITS));
}
template <unsigned BITS> inline uint32_t bchg(Regs& r, uint32_t v, uint32_t bit) {
    btst<BITS>(r, v, bit); return v ^ (1u << (bit % BITS));
}

// TAS: N,Z from the byte, V=C=0; caller writes back (v | 0x80).
inline uint32_t tas(Regs& r, uint32_t v) { return tst<B>(r, v) | 0x80u; }

} // namespace lift
} // namespace ms
'''
