// ms/linked.hpp - linked-build definitions for lifted code (ROADMAP 3.2b/3.2c).
//
// Force-included (-include ms/linked.hpp) into every src/lifted/** translation unit of the Amiga
// build with MS_LINK_GAME_ASM + MS_LINK_LIFTED.  It does what tools/lift.py documents for a linked
// build: predefine MS_SYM/MS_HUNK with the real linked addresses and supply the real callAsm.
//   MS_SYM(program, LAB_xxxx)  -> address of the linked symbol prg_LAB_xxxx   (mog -> mog_LAB_...)
//   MS_HUNK(mog, 1A)           -> address of the start of section mog_S_26     (hex hunk index)
// Symbols named through MS_SYM are the *thunk* when the routine is swapped (tools/thunks.py), so a
// pointer to a swapped routine stays valid for indirect calls.
#pragma once
#include "ms/regs.hpp"

#define MS_PFX_program "prg_"
#define MS_PFX_mog     "mog_"
// A block-scope extern with an asm label per use: no declarations to generate, and C++ names
// for all 6,000+ asm labels stay out of the C++ namespace.
#define MS_SYM(bin, label) \
    ({ extern char ms_symref_##bin##_##label[] __asm__(MS_PFX_##bin #label); \
       (uint32_t)(__UINTPTR_TYPE__)ms_symref_##bin##_##label; })
// Section start addresses: src/rt/gen/hunk_tab.cpp (generated by tools/thunks.py --gen-static).
extern "C" unsigned char *const ms_hunk_program[];
extern "C" unsigned char *const ms_hunk_mog[];
#define MS_HUNK(bin, hh)   ((uint32_t)(__UINTPTR_TYPE__)ms_hunk_##bin[0x##hh])

// lift_ops.hpp defines an inline, trapping callAsm for host replay.  Rename that one away, include
// the header (its #pragma once keeps later includes inert) and define the real one afterwards.
#define callAsm ms_hostCallAsmTrap_
#include "ms/gen/lift_ops.hpp"
#undef callAsm

// Marshals a Regs into the 68k registers, JSRs `addr` and marshals the registers and CCR back
// (src/rt/thunks.cpp).  Declared here so lifted code needs nothing else.
extern "C" void ms_call_asm(ms::Regs* regs, uint32_t addr);
namespace ms {
namespace lift {
inline void callAsm(Regs& R, Mem&, uint32_t addr) { ms_call_asm(&R, addr); }
} // namespace lift
} // namespace ms
