#!/usr/bin/env python3
"""Replay recorded differential cases against the lifted C++ (host, clang++).

    py tools/diffharness/run_host.py              # every case file in tests/diff
    py tools/diffharness/run_host.py LAB_03CA     # selected labels
    py tools/diffharness/run_host.py --m68k-check # also compile lifted code with
                                                  # m68k-amiga-elf-g++ (needs PATH per AGENTS.md)

Compiles src/lifted/<binary>/**/*.cpp plus tests/diff/replay_main.cpp (modelled
on moonshard/tools/test_host.py).  A registry of
`extern "C" void lab_<LABEL>(ms::Regs&, ms::Mem&)` definitions is generated by
scanning the sources.  Labels with a case file but no lifted function are
reported as SKIP; labels that fail print the first mismatch (register, expected,
got, input case).  Exit status is non-zero on any failure or stale case file.
"""
import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import harness  # noqa: E402

ROOT = harness.ROOT
OUT = ROOT / "build" / "diff" / "host"
LIFTED = ROOT / "src" / "lifted"
DEFN = re.compile(r'extern\s+"C"\s+void\s+lab_(\w+)\s*\(')
# Escape hatch for macro-generated functions:  // registry: LAB_A LAB_B ...
MACRO_LABELS = re.compile(r'^\s*//\s*registry:\s*(.+)$', re.M)
FLAGS = ["-std=c++17", "-D_CRT_SECURE_NO_WARNINGS", "-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH", "-Wall", "-Wextra", "-Werror", "-fno-exceptions", "-fno-rtti",
         "-I", str(ROOT / "include")]


def scan():
    """-> {(binary, label): source path}"""
    found = {}
    for src in sorted(LIFTED.rglob("*.cpp")):
        binary = src.relative_to(LIFTED).parts[0]
        text = src.read_text()
        for m in DEFN.finditer(text):
            found[(binary, m.group(1))] = src
        for m in MACRO_LABELS.finditer(text):
            for lab in m.group(1).split():
                found[(binary, lab)] = src
    return found


def build(found):
    OUT.mkdir(parents=True, exist_ok=True)
    rows = "".join('    {"%s", "%s", &lab_%s},\n' % (b, l, l) for (b, l) in sorted(found))
    decls = "".join('extern "C" void lab_%s(ms::Regs&, ms::Mem&);\n' % l
                    for (_, l) in sorted(found))
    (OUT / "registry_table.inc").write_text(
        decls + "static const Entry kRegistry[] = {\n" + rows +
        '    {nullptr, nullptr, nullptr}};\n'
        "static const unsigned kRegistryCount = %d;\n" % len(found))
    # unique name per run: a previous replay.exe can still be locked (AV scan, hung run)
    exe = OUT / ("replay_%d_%d%s" % (os.getpid(), int(time.time()), ".exe" if os.name == "nt" else ""))
    cxx = os.environ.get("CXX", "clang++")
    srcs = sorted({str(p) for p in found.values()})
    cmd = [cxx, *FLAGS, "-I", str(OUT), str(ROOT / "tests" / "diff" / "replay_main.cpp"),
           *srcs, "-o", str(exe)]
    subprocess.run(cmd, check=True)
    return exe


def cleanup_exes(keep=None):
    """Best-effort removal of replay_*.exe left by earlier runs (locked ones are skipped)."""
    for p in OUT.glob("replay_*"):
        if keep is not None and p == keep:
            continue
        try:
            p.unlink()
        except OSError:
            pass


def m68k_check(found):
    gxx = "m68k-amiga-elf-g++"
    for src in sorted({str(p) for p in found.values()}):
        subprocess.run([gxx, "-std=c++17", "-m68000", "-Os", "-fno-exceptions", "-fno-rtti",
                        "-Wall", "-Wextra", "-Werror", "-I", str(ROOT / "include"),
                        "-c", src, "-o", str(OUT / "m68k_check.o")], check=True)
        print("m68k-amiga-elf-g++ OK:", Path(src).relative_to(ROOT))


def run(labels=(), m68k=False):
    """Replay every case file.  -> (exit status, {(binary, label): (result, ncases)}) with result
    PASS | FAIL | SKIP | STALE.  Also writes build/diff/host/results.json (read by tools/status.py)."""
    found = scan()
    exe = build(found)
    results = {}
    try:
        if m68k:
            m68k_check(found)
        hashes = {}
        status = 0
        ran = 0
        for casefile in sorted((ROOT / "tests" / "diff").glob("*/*.json")):
            binary, label = casefile.parent.name, casefile.stem
            if labels and label not in labels:
                continue
            if (binary, label) not in found:
                print("SKIP %s/%s (no lifted function)" % (binary, label))
                results[(binary, label)] = ("SKIP", 0)
                continue
            doc = json.loads(casefile.read_text())
            n = len(doc["cases"])
            if binary not in hashes:
                img, _ = harness.load_image(ROOT / "build" / "reasm" / binary)
                hashes[binary] = hashlib.sha1(img).hexdigest()
                (ROOT / "build" / "diff").mkdir(parents=True, exist_ok=True)
                (ROOT / "build" / "diff" / (binary + ".img")).write_bytes(img)
            if doc["image"]["sha1"] != hashes[binary]:
                print("FAIL %s/%s: stale case file (reassembled image changed); regenerate" %
                      (binary, label))
                status = 1
                results[(binary, label)] = ("STALE", n)
                continue
            txt = OUT / (binary + "_" + label + ".cases")
            txt.write_text(harness.cases_to_text(doc))
            ran += 1
            r = subprocess.run([str(exe), str(ROOT), label, binary, str(txt)])
            status |= r.returncode != 0
            results[(binary, label)] = ("PASS" if r.returncode == 0 else "FAIL", n)
        if ran == 0 and not labels:
            print("no case files with lifted functions found")
    finally:
        cleanup_exes()
    if not labels:
        (OUT / "results.json").write_text(json.dumps(
            {"%s/%s" % k: {"result": v[0], "cases": v[1]} for k, v in sorted(results.items())},
            indent=0))
    return status, results


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("labels", nargs="*")
    ap.add_argument("--m68k-check", action="store_true")
    args = ap.parse_args()
    status, _ = run(args.labels, args.m68k_check)
    sys.exit(status)


if __name__ == "__main__":
    main()
